### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by dxvid-pts** [VGVentures/property_change_notifier#17]
This is a request to add support for null safety to this package. 
See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

Currently there is an open pr: [https://github.com/martinrybak/property_change_notifier/pull/16](https://github.com/martinrybak/property_change_notifier/pull/16)

**Comment by viliusvig** [comment]
I'm depending on this package in a number of places, and as there are no alternatives, it would be great if @martinrybak could look at the PR

**Comment by martinrybak** [comment]
Status update: looking into supporting more than string types for properties.

**Comment by DennisH511** [comment]
> I'm depending on this package in a number of places, and as there are no alternatives, it would be great if @martinrybak could look at the PR

Same here. Just updated to Flutter 2.0.1 and all dependencies but getting a build failure from this package.

Would really appreciate an update. TIA

**Comment by martinrybak** [comment]
Hi all, I pushed up a branch `nullsafety` that implements null safety as well as supports generic types for properties. All tests are passing. The example project and readme have also been updated. The API is slightly more verbose as now a second generic parameter is required. Unfortunately Dart does not allow for [default generic types](https://github.com/dart-lang/language/issues/363), although type aliases are [coming soon](https://github.com/dart-lang/sdk/issues/44951). For now we could potentially create convenience classes that use `String` behind the scenes, i.e. `StringPropertyChangeProvider<MyModel>` and `StringPropertyChangeConsumer<MyModel>`. Let me know your thoughts on this and the implementation in general. Thanks!

**Comment by GauteHaugen** [comment]
Would it be possible to push the `nullsafety` branch as a beta build on pub.dev?

**Comment by LaneQan** [comment]
Could you upload beta build with null-safety? Thanks.

**Comment by rossHell** [comment]
Thanks ! this branch saved my life !!!

Note that I had a crash 
```
Could not find an ancestor PropertyChangeProvider<MyType, MyTypeProperties>
'package:property_change_notifier/src/property_change_provider.dart':
Failed assertion: line 47 pos 14: 'model != null' 
```
That was caused because I had `PropertyChangeProvider(value: ..., child: ...)` somewhere in my code, missing template types. 
Replacing by `PropertyChangeProvider<MyType, MyTypeProperties>(...)` fixed the issue. Sry if that's obvious, but that was working without null safety so maybe it will helps someone having the same issue. 

Another point, getting value without listening doesn't work for me wihtout adding nullcheck operator. In your example you are doing this: 
`final model = PropertyChangeProvider.of<MyModel, String>(context, listen: false).value;`

but the compiler complains for "The property 'value' can't be unconditionally accessed because the receiver can be 'null'."
So I did it like this: 
`final model = PropertyChangeProvider.of<MyModel, String>(context, listen: false)!.value;`
If that a bad or wrong way  to do it ?

**Comment by martinrybak** [comment]
https://pub.dev/packages/property_change_notifier/versions/0.3.0
